package jetbrains.mps.samples.Kaja.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import jetbrains.mps.baseLanguage.logging.runtime.model.LoggingRuntime;
import org.apache.log4j.Level;
import org.iets3.core.expr.base.behavior.IETS3ExprEvalHelper;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;

public class Repeat_DataFlow extends DataFlowBuilder {
  private static final Logger LOG = LogManager.getLogger(Repeat_DataFlow.class);
  public void build(final DataFlowBuilderContext _context) {
    LoggingRuntime.logMsgView(Level.INFO, "" + as_ttq2a6_a0a1a0a0a1(IETS3ExprEvalHelper.evaluate(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x49a08c51fe543ccL, 0xbd998b46d641d7f5L, 0x2de971c785ecd14cL, 0x4771427f4e28e42bL, "alternate_count"))), Number.class).intValue(), Repeat_DataFlow.class, null, null);
    if (SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x49a08c51fe543ccL, 0xbd998b46d641d7f5L, 0x2de971c785ecd14cL, 0x2de971c785ecd14eL, "count")) < 0) {
      _context.getBuilder().emitJump(_context.getBuilder().label(_context.getNode(), "end"), "r:5784598d-868b-437e-9c58-15fb07e7f373(jetbrains.mps.samples.Kaja.dataFlow)/6630310702469930424");
    }
    _context.getBuilder().emitLabel("loopStart");
    _context.getBuilder().build((SNode) SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x49a08c51fe543ccL, 0xbd998b46d641d7f5L, 0x2de971c785ecd14cL, 0x2de971c785ecd14fL, "body")));
    _context.getBuilder().emitIfJump(_context.getBuilder().label(_context.getNode(), "loopStart"), "r:5784598d-868b-437e-9c58-15fb07e7f373(jetbrains.mps.samples.Kaja.dataFlow)/6630310702469940985");
    _context.getBuilder().emitLabel("end");
  }
  private static <T> T as_ttq2a6_a0a1a0a0a1(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
